# =============================================================================
# TechPotli Cart Service Kubernetes Deployment
# Production-ready deployment with scaling and health checks
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: techpotli
  labels:
    app: cart-service
    tier: backend
    version: v1.0.0
    environment: production
  annotations:
    description: "Cart Service Deployment for TechPotli E-commerce Platform"
    owner: "techpotli-engineering-team"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cart-service
      tier: backend
  template:
    metadata:
      labels:
        app: cart-service
        tier: backend
        version: v1.0.0
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
    spec:
      # Pod Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      
      # Container Security Context
      containers:
      - name: cart-service
        image: techpotli/cart-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3003
          protocol: TCP
        - name: metrics
          containerPort: 3003
          protocol: TCP
        
        # Environment Variables
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_PORT
          value: "3003"
        - name: APP_HOST
          value: "0.0.0.0"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: techpotli-db-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techpotli-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techpotli-redis-secret
              key: REDIS_PASSWORD
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: techpotli-config
              key: KAFKA_BROKERS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: techpotli-jwt-secret
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          value: "15m"
        - name: CORS_ORIGIN
          value: "https://techpotli.com,https://www.techpotli.com"
        
        # Resource Limits and Requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health Checks
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3003
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3003
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # Startup Probe
        startupProbe:
          httpGet:
            path: /health
            port: 3003
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        # Volume Mounts
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        
        # Security Context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
              - ALL
        
        # Lifecycle Hooks
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 10"
      
      # Volumes
      volumes:
      - name: config-volume
        configMap:
          name: techpotli-cart-service-config
      - name: logs-volume
        emptyDir: {}
      
      # Image Pull Secrets
      imagePullSecrets:
      - name: techpotli-registry-secret
      
      # Node Selector
      nodeSelector:
        node-role: backend
      
      # Tolerations
      tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "backend"
        effect: "NoSchedule"
      
      # Affinity
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cart-service
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - backend
                - worker
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: techpotli
  labels:
    app: cart-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
  - name: metrics
    port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: cart-service
    tier: backend
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
  namespace: techpotli
  labels:
    app: cart-service
    tier: backend
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
